### ISSUE TITLE
Results not repeatable?

### ISSUE THREAD

**Issue by ghost** [david-gpu/deep-makeover#10]
Results not repeatable?

I installed all the necessary files and started it with the default values. Training worked fine I assume (trained for 3 hours), final training batch looks like this: 
![batch000140_out](https://user-images.githubusercontent.com/25714601/28249543-05403f84-6a58-11e7-9f52-5c2d41f4dab0.png)

But when I open an image for inference, in this case image number 201739 from the celeb a dataset, the result of the inference (which should be male to female) is:
![inference_out](https://user-images.githubusercontent.com/25714601/28249551-2bc3b23a-6a58-11e7-8b24-c9417901a947.png)

Can you tell me what is going wrong?

**Comment by david-gpu** [comment]
Based on the last training batch it definitely looks like the model has not
converged yet. Notice that the right image in each image pair looks bad.

What kind of hardware are you using for training? To train in 3 hours you
need a high-end GPU.

**Comment by ghost** [comment]
I had the same hunch, so I trained it on my lab computer, again for 3 hours, this time with better results: 
![batch001140_out](https://user-images.githubusercontent.com/25714601/28266020-178038b6-6af3-11e7-9b3f-d42eac6deb3c.png)

and the inference of:
![202534](https://user-images.githubusercontent.com/25714601/28266033-27cf63c2-6af3-11e7-932b-18b8a0532d90.jpg)
resulted in:
![inference_out](https://user-images.githubusercontent.com/25714601/28266041-366462b6-6af3-11e7-9612-144fa49684a9.png)

which could possibly already be the start of a male->female translation, I guess I will just let it train for a day now and see if it works then

**Comment by ghost** [comment]
after having it train for 1440 hours still no luck, the latest training batch (20k+) looks like this:
![image](https://user-images.githubusercontent.com/25714601/28318673-e67dedb0-6bcb-11e7-8c59-ea5d8c14ec57.png)

and when I try to inference, it says `Operation 'None' not supported`

But even without the error, I guess, since it always starts training fresh from the start, it seems like this code is unusable for me =/

**Comment by david-gpu** [comment]
I don't know why your model isn't converging. In the readme I suggested training for "40,000 to 50,000 batches", perhaps that's the reason? As for training from the start, you could easily add some code to load the existing checkpoints.

These toy projects are provided as-is. I don't have the bandwidth to maintain them. Sorry.
