### ISSUE TITLE
Longer training and higher resolution images?

### ISSUE THREAD

**Issue by subzerofun** [david-gpu/deep-makeover#4]
Hey i finally got your code running – the results are really amazing! Will show them to my boss on monday :-)

I have a few questions/requests: 

---

**Longer training – better results?**
What would i need to change in the files to let the training run longer, to get better results? It was also interesting that my gtx 780 (like your 1080) only took 2 hours to complete the training. I thought an older gpu would take a lot more time.

Does a longer training get you clearer pictures (less artifacts)?

---

**Higher resolution images**
Would it be possible to generate images with 2x or larger resolution? I know you would also need high res training images – but i think there is another version of the celeba dataset with bigger pictures (i found two archives with ~12gb, but haven't downloaded them yet).

What would i need to modify in your files?

---

**Pictures with full head, not only cropped below hair**
Would this also be possible? It would be nice to get a bigger frame of the person. Or does your code only work for facial features?

---

**Input arguments for image generation**
Could you please add a few lines to your readme on what options you can use to generate the output?

---

Hope i'm not asking too much – but it would be great if you could generate images that could be printed. At least on a small scale. I know i could also use a neural net project to increase the resolution (your srez code) – but it's hard to get much more detail out of a 80x100px file.

Thanks again for your work! I really enjoy testing your projects, the srez one also was fun to try out!

**Comment by david-gpu** [comment]
> What would i need to change in the files to let the training run longer, to get better results?

Look at the `--train_time` option in `dm_flags.py`. You can change its value through the command line options.

>  It was also interesting that my gtx 780 (like your 1080) only took 2 hours to complete the training.

It trains for two hours by default. You can change the training time as indicated above.

> Does a longer training get you clearer pictures (less artifacts)?

Up to a point. After a while the GAN tends to produce less diverse images. The sweet spot appears to be around 40,000 to 50,000 batches.

> Would it be possible to generate images with 2x or larger resolution? I know you would also need high res training images

Right, you would need a larger dataset. The dataset loading code is in `dm_celeba.py` and `dm_input.py`. With larger input images you will also need a larger model and more training time.

> Pictures with full head, not only cropped below hair

There are good reasons why the images were cropped. You can play with it by modifying `dm_input.py`.

> Input arguments for image generation

Please read `dm_flags.py`.

**Comment by subzerofun** [comment]
Thanks for the quick reply! Should have just looked in `dm_flags.py` 🙃

Looked through the code to see if i can change the training/output resolution myself and the only obvious place i found is:

```python
    size_x, size_y = 80, 100
```
in `dm_input.py`. And of course the vars `off_x, off_y ` for cropping.

The `dm_model.py` code is a little bit too much for me – i don't have that much experience with tensorflow or neural net models in general (i know i could start with the tensorflow beginner tutorials, the docs are quite extensive). But to save time could you please highlight the lines of `dm_model.py` that i should look into?

--- 

PS: If you haven't seen this yet, this paper maybe could be interesting for you – it tries to do a similar thing like your srez project:

**Pixel Recursive Super Resolution**
> Abstract: We present a pixel recursive super resolution model that synthesizes realistic details into images while enhancing their resolution. A low resolution image may correspond to multiple plausible high resolution images, thus modeling the super resolution process with a pixel independent conditional model often results in averaging different details--hence blurry edges. By contrast, our model is able to represent a multimodal conditional distribution by properly modeling the statistical dependencies among the high resolution image pixels, conditioned on a low resolution input. We employ a PixelCNN architecture to define a strong prior over natural images and jointly optimize this prior with a deep conditioning convolutional network. Human evaluations indicate that samples from our proposed model look more photo realistic than a strong L2 regression baseline.

https://arxiv.org/pdf/1702.00783v1.pdf
https://arxiv.org/abs/1702.00783
