### ISSUE TITLE
Where I can get Large-scale CelebFaces Attributes (CelebA) Dataset ???

### ISSUE THREAD

**Issue by danchokobo** [david-gpu/deep-makeover#6]
I don't understand where I can get this dataset?
After you have the required software above you will also need the Large-scale CelebFaces Attributes (CelebA) Dataset. The model expects the Align&Cropped Images version. Extract all images to a subfolder named dataset. I.e. deep-makeover/dataset/lotsoffiles.jpg.

**Comment by rafariva** [comment]
http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

**Comment by yiaoyiyou** [comment]
https://pan.baidu.com/s/1eSNpdRG#list/path=%2F

**Comment by akkshita** [comment]
> http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

Too many requests

Sorry, this link has been automatically turned off for now. Learn more about traffic limits. 



this is shown by website while tryong to download dataset of Align&Cropped Images version

**Comment by karthikziffer** [comment]
https://www.kaggle.com/jessicali9530/celeba-dataset
