### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by danchokobo** [david-gpu/deep-makeover#7]
@david-gpu 
I download Large-scale CelebFaces Attributes (CelebA) Dataset from here = > http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html
and I dropped all images to dataset and created list_attr_celeba.txt file.
But I have that problem when running  command "python3 dm_main.py --run train" =>

> Traceback (most recent call last):
>   File "dm_main.py", line 169, in <module>
>     tf.app.run()
>   File "/Users/oteldanagul/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 43, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "dm_main.py", line 159, in main
>     train_data = _get_train_data()
>   File "dm_main.py", line 93, in _get_train_data
>     source_images = dm_input.input_data(sess, 'train', selected)
>   File "/Users/oteldanagul/Downloads/deep-makeover-master/dm_input.py", line 11, in input_data
>     assert mode == 'inference' or len(filenames) >= FLAGS.test_vectors
> AssertionError

**Comment by subzerofun** [comment]
Hey maybe i can help. You said you have **created** the `list_attr_celeba.txt` file – did you download the `list_attr_celeba.txt` file or did you just create an empy file? The file contains quite a lot of data that's crucial for the training. You can download the txt files from my working dataset folder here: https://we.tl/fhGdPXS79t and try it again.

The file should look like this:
```
202599
5_o_Clock_Shadow Arched_Eyebrows Attractive Bags_Under_Eyes Bald Bangs Big_Lips Big_Nose Black_Hair Blond_Hair Blurry Brown_Hair Bushy_Eyebrows Chubby Double_Chin Eyeglasses Goatee Gray_Hair Heavy_Makeup High_Cheekbones Male Mouth_Slightly_Open Mustache Narrow_Eyes No_Beard Oval_Face Pale_Skin Pointy_Nose Receding_Hairline Rosy_Cheeks Sideburns Smiling Straight_Hair Wavy_Hair Wearing_Earrings Wearing_Hat Wearing_Lipstick Wearing_Necklace Wearing_Necktie Young 
000001.jpg -1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1  1 -1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1 -1  1 -1  1 -1 -1  1
000002.jpg -1 -1 -1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 
(... and a lot more lines 😀 )
```

**Comment by subzerofun** [comment]
Just look at your errors: line 159 of `dm_main.py` starts loading the training files:
```python
train_data = _get_train_data()
```
line 93 sets the source images:
```python
source_images = dm_input.input_data(sess, 'train', selected)
```

next, on line 11 of `dm_input.py`:

```python
    assert mode == 'inference' or len(filenames) >= FLAGS.test_vectors
```

So maybe the filenames (and features) can't get loaded because your `list_attr_celeba.txt` is empty?

**Comment by danchokobo** [comment]
@subzerofun Hi! so I downloaded your files and put it in dataset,
Then again run it =>

>    69714 source images selected
>    78610 target images selected
> 
> Generator input (feature) size is 100 x 80 x 3 = 24000
> Generator has 0.59M parameters
> 
> Discriminator input (feature) size is 100 x 80 x 3 = 24000
> Discriminator has 0.84M parameters
> 
> Traceback (most recent call last):
>   File "dm_main.py", line 169, in <module>
>     tf.app.run()
>   File "/Users/oteldanagul/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 43, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "dm_main.py", line 159, in main
>     train_data = _get_train_data()
>   File "dm_main.py", line 106, in _get_train_data
>     train_model  = dm_model.create_model(sess, source_images, target_images, annealing, verbose=True)
>   File "/Users/oteldanagul/Downloads/deep-makeover-master/dm_model.py", line 214, in create_model
>     gene_loss = _generator_loss(source_images, gene_out, disc_fake_out, annealing)
>   File "/Users/oteldanagul/Downloads/deep-makeover-master/dm_model.py", line 135, in _generator_loss
>     gene_adversarial_loss = tf.nn.sigmoid_cross_entropy_with_logits(logits=disc_fake_output, labels=tf.ones_like(disc_fake_output))
> TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'

**Comment by danchokobo** [comment]
@david-gpu  @subzerofun  I updated version of tensorflow, then I have thats kind of results:
Am I on right way of processing images????

![2017-02-08 13 50 59](https://cloud.githubusercontent.com/assets/16972272/22727952/af1845a8-ee05-11e6-96bc-0339c8670079.png)

**Comment by subzerofun** [comment]
David wrote in the readme:

> I recommend training the model for about 40,000 to 50,000 batches.

> You will need to adjust --train_time depending on how many batches/hour your system can train.

> Each of these two examples were made after training a model for just two hours on one GTX 1080 GPU.


The default training time is 120min. But how far the training gets, how many batches are generated depends on the speed of your system (GPU or CPU). David uses the fastest consumer card from Nvidia out there, the GTX 1080 with 8 GB VRAM.

Does your Mac even have a Nvidia graphics card? Have you installed [CUDA](http://www.nvidia.com/object/cuda_home_new.html)? 

iMac or MacBook – which model?

Computation on a (recent) GPU is significantly faster than on the CPU. 
Read here why:
https://www.quora.com/Why-are-GPUs-well-suited-to-deep-learning
http://navoshta.com/cpu-vs-gpu/

So if you don't have a GPU (or haven't configured it) Thenao will use your CPU.

My Nvidia GTX 780 generated 16 batch pngs in 25min (batch nr. 3000).
So if you let it run on your machine for two hours and only got 3 pngs, then your MacBook/iMac is simply too slow! As David said, you need 40,000 to 50,000 batches to get good results. If you got 3 pngs in 120min, then you only have trained 400 batches. That's not enough to generate believable images!

This code is intended for training on the GPU – or on a powerful multicore processor.

**Check if your Mac has a graphics card – then try to install CUDA (for Nvidia) or OpenCL (for AMD) and configure it for Theano.**
http://deeplearning.net/software/theano/tutorial/using_gpu.html
